### ISSUE TITLE
getRel() term parameter finds 100% match for very vague search terms

### ISSUE THREAD

**Issue by prioberoi** [CommerceDataService/eu.us.opendata#22]
If a long nonsense search term is passed to getRel(), I get:
`
Search: No matches
`
which makes sense.

If I enter a super vague term like:
`
dataset <- getRel('a', lucky = T, beaKey = beaKey)
`
I get a 100% match.
`
[1] "Search duration: 0.013s"
[1] "Top match for 'a': 100% = Annual GDP by MSA/Metropolitan regions"
`

**Comment by SigmaMonstR** [comment]
At the moment, search is calculated on a relative score with respect to the query. We'll work on making it an absolute score.
