### ISSUE TITLE
R documentation for searchRel()

### ISSUE THREAD

**Issue by prioberoi** [CommerceDataService/eu.us.opendata#23]
It may be helpful to update the R help doc for searchRel to indicate that users can get the full relationship table by using a wildcard search term (*), and indicate whether this supports regex.

`
> searchRel('*')
[1] "Search duration: 0.019s"
  Rel_score               Rel_ID                                         Rel_name
1       100 <JOINT#COMP_EMP_A_2> Annual compensation of employees by State/NUTS 2
2       100 <JOINT#DISP_INC_A_2>         Annual disposable income by State/NUTS 2
3       100      <JOINT#GDP_A_4>           Annual GDP by MSA/Metropolitan regions
4       100      <JOINT#GDP_A_2>                       Annual GDP by State/NUTS 2
5       100      <JOINT#POP_A_3>                       Population by County/NUTS3
6       100      <JOINT#POP_A_2>                        Population by State/NUTS2
7       100      <JOINT#SAL_A_3>       Wage and salary employment by County/NUTS3
8       100      <JOINT#SAL_A_2>        Wage and salary employment by State/NUTS2
> 
`

**Comment by SigmaMonstR** [comment]
Will include the wildcard term in the documentation. Note that the library search is designed for probabilistic term matching for general search as opposed to structural matching.
