### ISSUE TITLE
US vs United States

### ISSUE THREAD

**Issue by SigmaMonstR** [CommerceDataService/eu.us.opendata#6]
How to resolve 'US' records in the Eurostat data versus 'United States' records in BEA data?

**Comment by DreaJulca** [comment]
Actually, US shouldn't be there at all, since it is neither NUTS 2 nor NUTS 3 comparable; I removed it from the response.

Also, fixed EU name mapping so that Eurostat geo_name is populated with full labels rather than codes or NAs.
